apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 4  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: shailesh49/hotstar:bf1a93f96f594146f98f5727eb5a273aec7d28ca
        ports:
        - containerPort: 3000  # Port your application listens on
