apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: shailesh49/hotstar:205a471a500018542bb3e93d796ab180ba0b92ab
        ports:
        - containerPort: 3000  # Port your application listens on
