apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 4  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: shailesh49/hotstar:1fc73b53ad1de6fad28ee8f58dc0d89997919061
        ports:
        - containerPort: 3000  # Port your application listens on
