apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: shailesh49/hotstar:3f6cc35a9cf188019634d68399bf757653b836c0
        ports:
        - containerPort: 3000  # Port your application listens on
