apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: hotstar
  template:
    metadata:
      labels:
        app: hotstar
    spec:
      containers:
      - name: hotstar
        image: shailesh49/hotstar:53c6ddb62a2d2a6a1e13ee3f08c65fbea97988eb
        ports:
        - containerPort: 3000  # Port your application listens on
