apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotstar-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: hotstar.aarshi.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hotstar-stable
                port:
                  number: 80
