name: CD - Deploy

on:
  workflow_dispatch:
    inputs:
      IMAGE_NAME:
        description: "Docker image to deploy"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Clean workspace → GitHub provides a fresh one each run 3333
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }} # personal access token or PAT with repo write access
      

      - name: Verify Docker Image Tags
        run: |
          echo "DOCKER_IMAGES: ${{ github.event.inputs.IMAGE_NAME }}"
             
      - name: Update Kubernetes manifests
        run: |
          cd Kubernetes
          sed -i "s|shailesh49/hotstar:[^\"']*|${{ env.IMAGE_NAME }}|g" deployment.yml


      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          echo "Checking repository status: "
          git status

          echo "Adding changes to git: "
          git add .

          echo "Committing changes: "
          git commit -m "Updated deployment image to ${{ env.IMAGE }}" || echo "No changes to commit"

          echo "Pushing changes to GitHub: "
          git push origin main
